apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: petclinic
data:
  nginx.conf: |
    pid /tmp/nginx.pid;

    events {}

    http {
      include /etc/nginx/mime.types;
      resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

      server {
        listen 8080;

        location = /healthz {
          return 200 "ok\n";
        }

        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          set $petclinic "petclinic.petclinic.svc.cluster.local";
          proxy_pass http://$petclinic;
        }
      }
    }
